# Generated by Django 6.0.3 on 2026-03-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_type', models.CharField(max_length=10)),
                ('organ_type', models.CharField(max_length=100)),
                ('medical_history', models.TextField()),
                ('urgency_level', models.IntegerField(help_text='Higher number = more urgent')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospitals.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='donor_profile', serialize=False, to='patients.patient')),
                ('consent_status', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recipient_profile', serialize=False, to='patients.patient')),
                ('waiting_list_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('MATCHED', 'Matched')], max_length=20)),
            ],
        ),
    ]
