# Generated by Django 6.0.3 on 2026-03-18 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Some tests like Crossmatch expire in 48-72 hours', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('GENERAL', 'General Health'), ('BLOOD_WORK', 'Detailed Blood Analysis'), ('HLA_TYPING', 'HLA Tissue Typing'), ('CROSSMATCH', 'Crossmatch Test'), ('IMAGING', 'Radiology/Imaging')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='lab_results',
            field=models.JSONField(help_text="Flexible schema. For HLA, use keys like 'hla_a', 'hla_b', etc."),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
