# Generated by Django 6.0.3 on 2026-03-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExchangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_hospital', models.CharField(max_length=255)),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_logs', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
